import { useMemo, useState } from 'react';
import styles from './App.module.css';
import Flag from './components/Flag/Flag';
import { randomAthleteName } from './data/chronicleNames';

type Phase='between'|'host'|'games'|'complete'; type Gender='M'|'W';
type EventKind='race'|'attempt'|'judged'|'team';
type Athlete={id:string;name:string;country:string;gender:Gender;sport:string;event:string;born:number;overall:number;potential:number;form:number;trait:string;medals:number;golds:number;retired:boolean};
type Medal={gold:number;silver:number;bronze:number};
type Result={athleteId?:string;name:string;country:string;mark:string;medal:'gold'|'silver'|'bronze'};
type FinalEvent={id:string;day:number;sport:string;name:string;gender:Gender;kind:EventKind;star:boolean;stars:number;hook:string;contenders:string[];resolved:boolean;results:Result[];progress?:number[][];roundScores?:number[][];teamScores?:number[][];headline?:string};
type Story={title:string;text:string;tone:'gold'|'blue'|'red'|'green'};
type Archive={year:number;host:string;champion:string;memory:string};
type Save={version:2;year:number;phase:Phase;host:string;day:number;athletes:Athlete[];events:FinalEvent[];medals:Record<string,Medal>;stories:Story[];history:Archive[]};

const COUNTRIES=['USA','GBR','FRA','GER','SWE','FIN','ITA','GRE','HUN','AUS','CAN','JPN','CHN','RUS','NED','BEL','DEN','NOR','ESP','BRA','ARG','CUB','MEX','IND','KOR','KEN','ETH','RSA','NZL','JAM','TUR','POL','CZE','SUI','AUT','IRL'];
const COUNTRY_NAMES:Record<string,string>={USA:'United States',GBR:'Great Britain',FRA:'France',GER:'Germany',SWE:'Sweden',FIN:'Finland',ITA:'Italy',GRE:'Greece',HUN:'Hungary',AUS:'Australia',CAN:'Canada',JPN:'Japan',CHN:'China',RUS:'Russia',NED:'Netherlands',BEL:'Belgium',DEN:'Denmark',NOR:'Norway',ESP:'Spain',BRA:'Brazil',ARG:'Argentina',CUB:'Cuba',MEX:'Mexico',IND:'India',KOR:'South Korea',KEN:'Kenya',ETH:'Ethiopia',RSA:'South Africa',NZL:'New Zealand',JAM:'Jamaica',TUR:'Turkey',POL:'Poland',CZE:'Czechia',SUI:'Switzerland',AUT:'Austria',IRL:'Ireland'};
const HOST_CANDIDATES:Record<number,string[]>={1900:['Paris','Berlin','Brussels'],1904:['St. Louis','Chicago','New York'],1908:['London','Rome','Stockholm'],1912:['Stockholm','Berlin','Budapest']};
const HOSTS=['Athens','Paris','St. Louis','London','Stockholm','Antwerp','Amsterdam','Los Angeles','Berlin','Helsinki','Rome','Tokyo','Mexico City','Munich','Montreal','Moscow','Seoul','Barcelona','Atlanta','Sydney','Athens','Beijing','London','Rio de Janeiro','Tokyo','Paris','Los Angeles','Brisbane'];
const TRAITS=['Fearless finisher','Technical perfectionist','Slow starter','Big-stage performer','Relentless veteran','Explosive prodigy','Calm under pressure','Late-race closer'];
const blankMedals=()=>Object.fromEntries(COUNTRIES.map(c=>[c,{gold:0,silver:0,bronze:0}]));
const rand=(n:number)=>Math.floor(Math.random()*n); const pick=<T,>(a:T[])=>a[rand(a.length)]; const age=(a:Athlete,y:number)=>y-a.born;
const eraFor=(y:number)=>y<1920?'The Founding Era':y<1948?'The Interwar Games':y<1992?'The Broadcast Age':y<2032?'The Global Games':'The Unwritten Future';
const countryPool=(year:number)=>COUNTRIES.slice(0,year<1900?14:year<1920?22:year<1960?28:COUNTRIES.length);
const sportProgram=(y:number)=>['Athletics','Cycling','Fencing','Gymnastics','Shooting','Swimming','Tennis','Weightlifting','Wrestling',...(y>=1900?['Rowing']:[]),...(y>=1904?['Boxing','Diving']:[]),...(y>=1936?['Basketball']:[]),...(y>=1964?['Judo','Volleyball']:[]),...(y>=1984?['Rhythmic Gymnastics']:[]),...(y>=2000?['Taekwondo']:[])];

type EventTemplate={sport:string;name:string;gender:Gender;kind:EventKind;from:number};
const TEMPLATES:EventTemplate[]=[
 {sport:'Athletics',name:"Men's 100m",gender:'M',kind:'race',from:1896},{sport:'Athletics',name:"Men's 400m",gender:'M',kind:'race',from:1896},{sport:'Athletics',name:"Men's 1500m",gender:'M',kind:'race',from:1896},{sport:'Athletics',name:"Men's Marathon",gender:'M',kind:'race',from:1896},{sport:'Athletics',name:"Men's High Jump",gender:'M',kind:'attempt',from:1896},{sport:'Athletics',name:"Men's Long Jump",gender:'M',kind:'attempt',from:1896},{sport:'Athletics',name:"Men's Javelin",gender:'M',kind:'attempt',from:1908},
 {sport:'Swimming',name:"Men's 100m Freestyle",gender:'M',kind:'race',from:1896},{sport:'Swimming',name:"Men's 400m Freestyle",gender:'M',kind:'race',from:1896},{sport:'Cycling',name:"Men's Track Sprint",gender:'M',kind:'race',from:1896},{sport:'Cycling',name:"Men's Road Race",gender:'M',kind:'race',from:1896},
 {sport:'Gymnastics',name:"Men's All-Around",gender:'M',kind:'judged',from:1896},{sport:'Fencing',name:"Men's Foil",gender:'M',kind:'judged',from:1896},{sport:'Weightlifting',name:"Men's Heavyweight",gender:'M',kind:'attempt',from:1896},{sport:'Wrestling',name:"Men's Greco-Roman",gender:'M',kind:'judged',from:1896},{sport:'Shooting',name:"Men's Rifle",gender:'M',kind:'attempt',from:1896},{sport:'Tennis',name:"Men's Singles",gender:'M',kind:'team',from:1896},
 {sport:'Rowing',name:"Men's Single Sculls",gender:'M',kind:'race',from:1900},{sport:'Boxing',name:"Men's Heavyweight",gender:'M',kind:'judged',from:1904},{sport:'Diving',name:"Men's Platform",gender:'M',kind:'judged',from:1904},
 {sport:'Athletics',name:"Women's 100m",gender:'W',kind:'race',from:1928},{sport:'Athletics',name:"Women's 800m",gender:'W',kind:'race',from:1928},{sport:'Gymnastics',name:"Women's All-Around",gender:'W',kind:'judged',from:1928},{sport:'Swimming',name:"Women's 100m Freestyle",gender:'W',kind:'race',from:1912},
 {sport:'Basketball',name:"Men's Tournament Final",gender:'M',kind:'team',from:1936},{sport:'Volleyball',name:"Women's Tournament Final",gender:'W',kind:'team',from:1964},{sport:'Judo',name:"Women's Middleweight",gender:'W',kind:'judged',from:1992}
];
const templatesFor=(y:number)=>TEMPLATES.filter(t=>t.from<=y);

function makeAthlete(year:number,t:EventTemplate,i:number):Athlete{
 const country=pick(countryPool(year)); const born=year-(18+rand(t.kind==='judged'?14:12));
 return {id:`${year}-${t.sport}-${t.name}-${i}-${Math.random()}`,name:randomAthleteName(country,t.gender),country,gender:t.gender,sport:t.sport,event:t.name,born,overall:67+rand(27),potential:78+rand(21),form:68+rand(29),trait:pick(TRAITS),medals:0,golds:0,retired:false};
}
function initialAthletes(year:number){return templatesFor(year).flatMap(t=>Array.from({length:6},(_,i)=>makeAthlete(year,t,i)));}
function storiesFor(year:number,athletes:Athlete[]):Story[]{const top=[...athletes].filter(a=>!a.retired).sort((a,b)=>b.potential-a.potential)[0];return [
 {title:'A name to remember',text:`${top?.name} of ${COUNTRY_NAMES[top?.country]||top?.country} is emerging as one of the age's great ${top?.sport.toLowerCase()} talents.`,tone:'blue'},
 {title:'The program evolves',text:year===1900?'Women appear in selected competitions and rowing expands the program.':year===1904?'Boxing and diving enter an increasingly ambitious Olympic program.':year===1928?"Women's athletics changes the movement forever.":`${sportProgram(year).length} sports now define the Olympic movement.`,tone:'gold'},
 {title:'A nation is rising',text:`${COUNTRY_NAMES[pick(countryPool(year))]} has invested in coaching and facilities before the next Games.`,tone:'green'},
 {title:'The old guard',text:'Established champions face younger challengers, and several careers may end at the next Games.',tone:'red'}]}
function contenderScore(a:Athlete,y:number){return a.overall+a.form*.18+Math.random()*17-Math.max(0,age(a,y)-33)*1.1}
function fieldFor(t:EventTemplate,athletes:Athlete[],year:number){let pool=athletes.filter(a=>!a.retired&&a.event===t.name&&a.gender===t.gender);while(pool.length<6){const a=makeAthlete(year,t,pool.length);athletes.push(a);pool.push(a)}return [...pool].sort((a,b)=>contenderScore(b,year)-contenderScore(a,year)).slice(0,5)}
function makeEvents(year:number,athletes:Athlete[]):FinalEvent[]{
 const list=templatesFor(year); const scored=list.map((t,i)=>{const field=fieldFor(t,athletes,year);const gap=field[0].overall-field[1].overall;const veteran=field.some(a=>age(a,year)>=33);const prior=field.some(a=>a.golds>=1);const drama=(gap<=3?3:0)+(veteran?2:0)+(prior?2:0)+Math.random()*3;return {t,i,field,drama}});
 const starIds=new Set(scored.sort((a,b)=>b.drama-a.drama).slice(0,Math.min(10,Math.max(8,Math.floor(list.length*.45)))).map(x=>x.i));
 return scored.sort((a,b)=>a.i-b.i).map(({t,i,field,drama})=>({id:`${year}-${i}`,day:1+(i%12),sport:t.sport,name:t.name,gender:t.gender,kind:t.kind,star:starIds.has(i),stars:starIds.has(i)?Math.min(6,3+Math.floor(drama/3)):1,hook:field.some(a=>age(a,year)>=33)?`${field.find(a=>age(a,year)>=33)?.name} may be appearing in a final Olympic Games.`:field[0].overall-field[1].overall<=3?'The leading contenders enter separated by almost nothing.':`${field[0].name} arrives as the favorite, but Olympic finals rarely follow the script.`,contenders:field.map(a=>a.id),resolved:false,results:[]}));
}
function markFor(e:FinalEvent,a:Athlete,year:number,rank:number){const era=(year-1896)/132;if(e.name.includes('100m'))return `${Math.max(9.45,12.35-era*2.4-(a.overall-70)*.018+rank*.09+Math.random()*.12).toFixed(2)}s`;if(e.name.includes('400m'))return `${Math.max(42.5,56-era*9-(a.overall-70)*.08+rank*.35+Math.random()*.5).toFixed(2)}s`;if(e.name.includes('1500m'))return `3:${String(Math.max(25,58-Math.round(era*20+(a.overall-70)*.18-rank*2))).padStart(2,'0')}.${rand(10)}`;if(e.name.includes('Marathon'))return `${Math.max(1,3-Math.floor(era))}:${String(Math.max(2,48-Math.floor(era*35)-(a.overall-70)/2+rank*3)).padStart(2,'0')}:${String(rand(60)).padStart(2,'0')}`;if(e.name.includes('High Jump'))return `${(1.65+era*.7+(a.overall-70)*.008-rank*.025+Math.random()*.015).toFixed(2)}m`;if(e.name.includes('Long Jump'))return `${(5.9+era*2.1+(a.overall-70)*.022-rank*.08+Math.random()*.04).toFixed(2)}m`;if(e.name.includes('Javelin'))return `${(48+era*42+(a.overall-70)*.35-rank*1.1+Math.random()).toFixed(2)}m`;if(e.kind==='judged')return `${(7.1+(a.overall-70)*.065-rank*.12+Math.random()*.18).toFixed(2)}`;return `${80+Math.round((a.overall-70)*1.4-rank*3+Math.random()*4)} pts`}
function resolveEvent(e:FinalEvent,athletes:Athlete[],year:number):FinalEvent{
 const field=e.contenders.map(id=>athletes.find(a=>a.id===id)!).filter(Boolean);const ranked=field.map(a=>({a,s:contenderScore(a,year)})).sort((a,b)=>b.s-a.s);const results=ranked.slice(0,3).map(({a},i)=>({athleteId:a.id,name:a.name,country:a.country,mark:markFor(e,a,year,i),medal:(['gold','silver','bronze'] as const)[i]}));
 const progress=e.kind==='race'?Array.from({length:e.name.includes('100m')?10:6},(_,tick)=>field.map((a,j)=>Math.max(0,Math.min(100,(tick+1)*(100/(e.name.includes('100m')?10:6))+(a.overall-ranked[0].a.overall)*.35+(Math.random()*5-2.5)-(j*.3))))):undefined;
 const roundScores=e.kind==='attempt'||e.kind==='judged'?Array.from({length:e.kind==='attempt'?5:4},()=>field.map((a,j)=>Math.max(0,+(6.8+(a.overall-70)*.065+Math.random()*.8-j*.025).toFixed(2)))):undefined;
 const teamScores=e.kind==='team'?Array.from({length:4},(_,q)=>[Math.round((q+1)*(18+Math.random()*8)),Math.round((q+1)*(18+Math.random()*8))]):undefined;
 const comeback=Math.random()<.35;return {...e,resolved:true,results,progress,roundScores,teamScores,headline:comeback?`${results[0].name} surged from behind to take gold.`:`${results[0].name} controlled the final and became Olympic champion.`};
}
function initialSave():Save{const athletes=initialAthletes(1896);return {version:2,year:1896,phase:'between',host:'Athens',day:0,athletes,events:[],medals:blankMedals(),stories:storiesFor(1896,athletes),history:[]}}

export default function App(){
 const [save,setSave]=useState<Save>(()=>{try{const x=JSON.parse(localStorage.getItem('olympic-chronicles-v2')||'null');return x?.version===2?x:initialSave()}catch{return initialSave()}});
 const [view,setView]=useState<'chronicle'|'games'|'athletes'|'almanac'>('chronicle'); const [watchId,setWatchId]=useState<string|null>(null); const [watchStep,setWatchStep]=useState(0);
 const persist=(s:Save)=>{setSave(s);localStorage.setItem('olympic-chronicles-v2',JSON.stringify(s))};
 const medalRows=useMemo(()=>(Object.entries(save.medals) as [string,Medal][]).sort((a,b)=>b[1].gold-a[1].gold||b[1].silver-a[1].silver||b[1].bronze-a[1].bronze),[save.medals]);
 const active=save.athletes.filter(a=>!a.retired).sort((a,b)=>b.overall-a.overall); const today=save.events.filter(e=>e.day===save.day); const watched=save.events.find(e=>e.id===watchId);
 function beginGames(host=save.host){const athletes=[...save.athletes];const events=makeEvents(save.year,athletes);persist({...save,host,phase:'games',day:1,athletes,events,medals:blankMedals()});setView('games')}
 function advance(){if(save.year%4===0){if(save.year===1896)beginGames('Athens');else persist({...save,phase:'host'});return}const y=save.year+1;let athletes=save.athletes.map(a=>({...a,form:66+rand(30),overall:Math.min(a.potential,a.overall+(Math.random()<.55?rand(2):0)),retired:a.retired||(age(a,y)>35&&Math.random()<.3)}));templatesFor(y).forEach(t=>{if(!athletes.some(a=>!a.retired&&a.event===t.name))athletes.push(...Array.from({length:5},(_,i)=>makeAthlete(y,t,i)))});persist({...save,year:y,phase:'between',host:HOSTS[Math.floor((y-1896)/4)%HOSTS.length]||pick(HOSTS),athletes,stories:storiesFor(y,athletes)});}
 function applyResolution(event:FinalEvent){let events=save.events.map(e=>e.id===event.id?event:e);let medals={...save.medals};let athletes=[...save.athletes];event.results.forEach(r=>{const m=r.medal;medals={...medals,[r.country]:{...medals[r.country],[m]:medals[r.country][m]+1}};if(r.athleteId)athletes=athletes.map(a=>a.id===r.athleteId?{...a,medals:a.medals+1,golds:a.golds+(m==='gold'?1:0)}:a)});persist({...save,events,medals,athletes})}
 function simulateNormal(){const unresolved=today.filter(e=>!e.star&&!e.resolved);if(unresolved.length){let s=save;unresolved.forEach(e=>{const r=resolveEvent(e,s.athletes,s.year);let medals={...s.medals};let athletes=[...s.athletes];r.results.forEach(x=>{medals={...medals,[x.country]:{...medals[x.country],[x.medal]:medals[x.country][x.medal]+1}};athletes=athletes.map(a=>a.id===x.athleteId?{...a,medals:a.medals+1,golds:a.golds+(x.medal==='gold'?1:0)}:a)});s={...s,events:s.events.map(x=>x.id===r.id?r:x),medals,athletes}});persist(s)}}
 function openWatch(e:FinalEvent){let event=e;if(!event.resolved){event=resolveEvent(event,save.athletes,save.year);applyResolution(event)}setWatchId(event.id);setWatchStep(0)}
 function nextDay(){if(today.some(e=>!e.resolved)){return}if(save.day>=12){persist({...save,phase:'complete'});return}persist({...save,day:save.day+1})}
 function nextCycle(){const champ=medalRows[0]?.[0]||'USA';const memory=save.events.filter(e=>e.star&&e.headline).slice(0,3).map(e=>e.headline).join(' ');const y=save.year+1;persist({...save,year:y,phase:'between',day:0,events:[],medals:blankMedals(),history:[...save.history,{year:save.year,host:save.host,champion:champ,memory:memory||`${COUNTRY_NAMES[champ]} led the medal table.`}],stories:storiesFor(y,save.athletes)});setView('chronicle')}
 const hostOptions=HOST_CANDIDATES[save.year]||[HOSTS[Math.floor((save.year-1896)/4)%HOSTS.length]||'Paris',pick(HOSTS),pick(HOSTS)];
 return <div className={styles.app}>
  <header className={styles.topbar}><div><span className={styles.kicker}>OLYMPIC</span><strong>CHRONICLES</strong></div><div className={styles.era}>{eraFor(save.year)} · {save.year}</div><button className={styles.reset} onClick={()=>{localStorage.removeItem('olympic-chronicles-v2');location.reload()}}>New history</button></header>
  <nav className={styles.nav}>{(['chronicle','games','athletes','almanac'] as const).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?styles.navActive:''}>{v}</button>)}</nav>
  {save.phase==='host'&&<div className={styles.hostOverlay}><div className={styles.hostPanel}><span className={styles.eyebrow}>Host selection · {save.year}</span><h1>Where will the world gather?</h1><p>Each candidate brings a home advantage and a distinct Olympic identity.</p><div className={styles.hostGrid}>{hostOptions.map((h,i)=><button key={`${h}-${i}`} onClick={()=>beginGames(h)}><small>CANDIDATE {i+1}</small><b>{h}</b><span>{i===0?'Traditional program':i===1?'Expanded demonstrations':'Bold international bid'}</span></button>)}</div></div></div>}
  {view==='chronicle'&&<main className={styles.layout}><section className={styles.hero}><div><span className={styles.eyebrow}>{save.year%4===0?`${save.host} awaits`:`${4-(save.year-1896)%4} years to the Games`}</span><h1>The world moves toward the next Olympiad.</h1><p>Champions age, new talents emerge, nations invest and the Olympic program expands with history.</p></div><div className={styles.yearCard}><small>THE YEAR</small><b>{save.year}</b><span>{sportProgram(save.year).length} active sports</span></div></section><section className={styles.section}><span className={styles.eyebrow}>Annual chronicle</span><h2>What changed this year</h2><div className={styles.storyGrid}>{save.stories.map((s,i)=><article className={`${styles.story} ${styles[s.tone]}`} key={i}><small>{s.title}</small><h3>{s.text}</h3></article>)}</div></section><section className={styles.split}><div className={styles.panel}><span className={styles.eyebrow}>Athletes to watch</span>{active.slice(0,5).map(a=><div className={styles.athleteRow} key={a.id}><Flag code={a.country} size={28}/><div><b>{a.name}</b><span>{COUNTRY_NAMES[a.country]} · {a.sport} · age {age(a,save.year)}</span></div><strong>{a.overall}</strong></div>)}</div><div className={styles.panel}><span className={styles.eyebrow}>Olympic evolution</span><h3>{sportProgram(save.year).length} sports now form the program</h3><div className={styles.sportCloud}>{sportProgram(save.year).map(s=><span key={s}>{s}</span>)}</div></div></section><button className={styles.primary} onClick={advance}>{save.year%4===0?(save.year===1896?'Open Athens 1896':'Select the next host'):'Advance one year'} <span>→</span></button></main>}
  {view==='games'&&<main className={styles.layout}><section className={styles.gamesHero}><div><span className={styles.eyebrow}>{save.host.toUpperCase()} {save.year}</span><h1>{save.phase==='complete'?'How history remembers these Games':`Day ${save.day} of 12`}</h1><p>{save.phase==='complete'?'The champions are crowned and the stories enter the archive.':'Every final on today’s program is shown below. Star events can be witnessed round by round.'}</p></div><div className={styles.rings}>◯ ◯ ◯ ◯ ◯</div></section><section className={styles.medalStrip}>{medalRows.slice(0,5).map(([c,m],i)=><div key={c}><span>{i+1}</span><Flag code={c} size={24}/><b>{c}</b><strong>{m.gold}</strong><small>gold</small></div>)}</section>{save.phase!=='complete'?<><div className={styles.dayNav}>{Array.from({length:12},(_,i)=>i+1).map(d=><button key={d} className={d===save.day?styles.dayActive:''} onClick={()=>setSave({...save,day:d})}>DAY {d}</button>)}</div><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>Daily program</span><h2>Finals on Day {save.day}</h2></div><span>{today.filter(e=>e.resolved).length}/{today.length} complete</span></div><div className={styles.eventGrid}>{today.map(e=><article key={e.id} className={`${styles.eventCard} ${e.star?styles.starCard:''}`}><div className={styles.eventTop}><span>{e.sport}</span><span>{e.star?'★'.repeat(e.stars):'FINAL'}</span></div><h3>{e.name}</h3><p>{e.resolved?e.headline:e.hook}</p>{e.resolved?<div className={styles.podiumMini}>{e.results.map(r=><div key={r.medal}><span>{r.medal==='gold'?'🥇':r.medal==='silver'?'🥈':'🥉'}</span><Flag code={r.country} size={22}/><b>{r.name}</b><em>{r.mark}</em></div>)}</div>:<div className={styles.favorite}>{e.star?<><b>{save.athletes.find(a=>a.id===e.contenders[0])?.name}</b><span>Marquee final</span></>:<><b>Athletes qualified</b><span>Ready to simulate</span></>}</div>}<button onClick={()=>e.star?openWatch(e):undefined} disabled={!e.star}>{e.star?(e.resolved?'Relive event':'Watch event'):(e.resolved?'Final complete':'Normal final')}</button></article>)}</div></section><div className={styles.actionRow}><button className={styles.secondary} onClick={simulateNormal}>Simulate normal finals</button><button className={styles.primary} onClick={nextDay}>{save.day>=12?'Close the Games':'Advance to next day'} →</button></div></>:<section className={styles.memory}><span className={styles.eyebrow}>The final chronicle</span><h2>{save.host} {save.year}: The Games of New Legends</h2><p>{save.events.filter(e=>e.star&&e.headline).slice(0,4).map(e=>e.headline).join(' ')}</p><button className={styles.primary} onClick={nextCycle}>Begin the next cycle →</button></section>}</main>}
  {view==='athletes'&&<main className={styles.layout}><section className={styles.section}><span className={styles.eyebrow}>Living careers</span><h1>Athletes of the age</h1><div className={styles.athleteGrid}>{active.slice(0,40).map(a=><article className={styles.athleteCard} key={a.id}><Flag code={a.country} size={34}/><small>{a.country} · {a.sport}</small><h3>{a.name}</h3><p>{a.event}</p><div className={styles.metrics}><span><b>{a.overall}</b> rating</span><span><b>{age(a,save.year)}</b> age</span><span><b>{a.golds}</b> gold</span></div><em>{a.trait}</em></article>)}</div></section></main>}
  {view==='almanac'&&<main className={styles.layout}><section className={styles.section}><span className={styles.eyebrow}>The historical archive</span><h1>Olympic Almanac</h1>{save.history.length===0?<div className={styles.empty}>No Games have entered the archive yet.</div>:<div className={styles.historyGrid}>{[...save.history].reverse().map(h=><article className={styles.historyCard} key={h.year}><small>{h.host}</small><h2>{h.year}</h2><b><Flag code={h.champion} size={22}/> {COUNTRY_NAMES[h.champion]} led the medal table</b><p>{h.memory}</p></article>)}</div>}</section></main>}
  {watched&&<WatchModal event={watched} athletes={save.athletes} year={save.year} step={watchStep} setStep={setWatchStep} close={()=>setWatchId(null)}/>} 
 </div>
}

function WatchModal({event,athletes,year,step,setStep,close}:{event:FinalEvent;athletes:Athlete[];year:number;step:number;setStep:(n:number)=>void;close:()=>void}){
 const field=event.contenders.map(id=>athletes.find(a=>a.id===id)!).filter(Boolean);const max=event.kind==='race'?(event.progress?.length||1)-1:event.kind==='team'?(event.teamScores?.length||1)-1:(event.roundScores?.length||1)-1;const done=step>max;
 return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.close} onClick={close}>×</button><span className={styles.eyebrow}>{event.sport} · {year}</span><h2>{event.name}</h2>{!done&&event.kind==='race'&&<><div className={styles.liveClock}>{event.name.includes('100m')?`${step+1}.0s`:`CHECKPOINT ${step+1}`}</div><div className={styles.liveRows}>{field.map((a,i)=>{const distance=event.progress?.[step]?.[i]||0;return <div key={a.id}><Flag code={a.country} size={26}/><b>{a.name}</b><span>{a.country}</span><strong>{event.name.includes('100m')?`${distance.toFixed(1)}m`:`${Math.round(distance)}%`}</strong><div className={styles.track}><i style={{width:`${distance}%`}}/></div></div>})}</div></>}{!done&&(event.kind==='attempt'||event.kind==='judged')&&<div className={styles.scoreTable}><div className={styles.scoreHead}><span>ATHLETE</span>{Array.from({length:(event.roundScores?.length||0)},(_,i)=><b key={i}>RD{i+1}</b>)}</div>{field.map((a,i)=><div key={a.id}><span><Flag code={a.country} size={23}/><b>{a.name}</b></span>{event.roundScores?.map((r,ri)=><em key={ri}>{ri<=step?r[i].toFixed(2):'—'}</em>)}</div>)}</div>}{!done&&event.kind==='team'&&<div className={styles.teamWatch}><div><Flag code={field[0]?.country} size={42}/><h3>{field[0]?.country}</h3><strong>{event.teamScores?.[step]?.[0]||0}</strong></div><span>{step===3?'FINAL':`Q${step+1}`}</span><div><Flag code={field[1]?.country} size={42}/><h3>{field[1]?.country}</h3><strong>{event.teamScores?.[step]?.[1]||0}</strong></div></div>}{done?<div className={styles.reveal}><small>OLYMPIC CHAMPION</small><h3>{event.results[0]?.name}</h3><div className={styles.championFlag}><Flag code={event.results[0]?.country} size={46}/>{COUNTRY_NAMES[event.results[0]?.country]}</div><b>{event.results[0]?.mark}</b><p>{event.headline}</p><div className={styles.finalPodium}>{event.results.map(r=><div key={r.medal}><span>{r.medal.toUpperCase()}</span><Flag code={r.country} size={24}/><b>{r.name}</b><em>{r.mark}</em></div>)}</div></div>:<button className={styles.primary} onClick={()=>setStep(step+1)}>{step===max?'Reveal champion':'Next '+(event.kind==='race'?'checkpoint':'round')} →</button>}</div></div>
}
