import {useMemo,useState} from 'react';
import styles from './App.module.css';
import Flag from './components/Flag/Flag';
import {randomAthleteName} from './data/chronicleNames';

type Gender='M'|'W'; type Kind='race'|'attempt'|'judged'|'team'; type Phase='between'|'games'|'complete';
type Athlete={id:string;name:string;country:string;gender:Gender;sport:string;event:string;born:number;overall:number;potential:number;form:number;trait:string;medals:number;golds:number;appearances:number;retired:boolean};
type Result={athleteId?:string;name:string;country:string;mark:string;medal:'gold'|'silver'|'bronze'};
type FinalEvent={id:string;day:number;sport:string;name:string;gender:Gender;kind:Kind;star:boolean;stars:number;hook:string;contenders:string[];resolved:boolean;results:Result[];progress?:number[][];roundScores?:number[][];teamScores?:number[][];headline?:string};
type Qualification={total:number;closed:number;counts:Record<string,number>;news:string[]};
type Archive={year:number;host:string;champion:string;memory:string};
type Save={version:3;year:number;olympicYear:number;host:string;pendingHost:boolean;phase:Phase;day:number;athletes:Athlete[];events:FinalEvent[];medals:Record<string,{gold:number;silver:number;bronze:number}>;qualification:Qualification;history:Archive[];annualNews:string[]};

const COUNTRIES=['USA','GBR','FRA','GER','SWE','FIN','ITA','GRE','HUN','AUS','CAN','JPN','CHN','RUS','NED','BEL','DEN','NOR','ESP','BRA','ARG','CUB','MEX','IND','KOR','KEN','ETH','RSA','NZL','JAM','TUR','POL','CZE','SUI','AUT','IRL'];
const NAMES:Record<string,string>={USA:'United States',GBR:'Great Britain',FRA:'France',GER:'Germany',SWE:'Sweden',FIN:'Finland',ITA:'Italy',GRE:'Greece',HUN:'Hungary',AUS:'Australia',CAN:'Canada',JPN:'Japan',CHN:'China',RUS:'Russia',NED:'Netherlands',BEL:'Belgium',DEN:'Denmark',NOR:'Norway',ESP:'Spain',BRA:'Brazil',ARG:'Argentina',CUB:'Cuba',MEX:'Mexico',IND:'India',KOR:'South Korea',KEN:'Kenya',ETH:'Ethiopia',RSA:'South Africa',NZL:'New Zealand',JAM:'Jamaica',TUR:'Turkey',POL:'Poland',CZE:'Czechia',SUI:'Switzerland',AUT:'Austria',IRL:'Ireland'};
const HOSTS=['Paris','St. Louis','London','Stockholm','Antwerp','Amsterdam','Los Angeles','Berlin','Helsinki','Rome','Tokyo','Mexico City','Munich','Montreal','Moscow','Seoul','Barcelona','Atlanta','Sydney','Athens','Beijing','London','Rio de Janeiro','Tokyo','Paris','Los Angeles','Brisbane'];
const HOST_COUNTRY:Record<string,string>={Paris:'FRA','St. Louis':'USA',London:'GBR',Stockholm:'SWE',Antwerp:'BEL',Amsterdam:'NED','Los Angeles':'USA',Berlin:'GER',Helsinki:'FIN',Rome:'ITA',Tokyo:'JPN','Mexico City':'MEX',Munich:'GER',Montreal:'CAN',Moscow:'RUS',Seoul:'KOR',Barcelona:'ESP',Atlanta:'USA',Sydney:'AUS',Athens:'GRE',Beijing:'CHN','Rio de Janeiro':'BRA',Brisbane:'AUS'};
const TRAITS=['Fearless finisher','Technical perfectionist','Slow starter','Big-stage performer','Relentless veteran','Explosive prodigy','Calm under pressure','Late-race closer'];
const rand=(n:number)=>Math.floor(Math.random()*n), pick=<T,>(a:T[])=>a[rand(a.length)], age=(a:Athlete,y:number)=>y-a.born;
const countryPool=(y:number)=>COUNTRIES.slice(0,y<1900?14:y<1920?22:y<1960?29:COUNTRIES.length);
const blankMedals=()=>Object.fromEntries(COUNTRIES.map(c=>[c,{gold:0,silver:0,bronze:0}]));

type Template={sport:string;name:string;gender:Gender;kind:Kind;from:number};
const A=(name:string,kind:Kind='race',from=1896,gender:Gender='M'):Template=>({sport:'Athletics',name:`${gender==='M'?"Men's":"Women's"} ${name}`,gender,kind,from});
const S=(sport:string,name:string,kind:Kind,from=1896,gender:Gender='M'):Template=>({sport,name:`${gender==='M'?"Men's":"Women's"} ${name}`,gender,kind,from});
const T:Template[]=[
 A('100m'),A('200m'),A('400m'),A('800m'),A('1500m'),A('Marathon'),A('110m Hurdles'),A('High Jump','attempt'),A('Pole Vault','attempt'),A('Long Jump','attempt'),A('Triple Jump','attempt'),A('Shot Put','attempt'),A('Discus','attempt'),A('Javelin','attempt',1908),
 S('Swimming','100m Freestyle','race'),S('Swimming','400m Freestyle','race'),S('Swimming','1500m Freestyle','race'),S('Swimming','100m Backstroke','race',1904),S('Swimming','200m Breaststroke','race',1904),
 S('Cycling','Track Sprint','race'),S('Cycling','10km Track','race'),S('Cycling','Road Race','race'),
 S('Gymnastics','All-Around','judged'),S('Gymnastics','Vault','judged'),S('Gymnastics','Parallel Bars','judged'),S('Gymnastics','Horizontal Bar','judged'),S('Gymnastics','Rings','judged'),
 S('Fencing','Foil','judged'),S('Fencing','Sabre','judged'),S('Fencing','Épée','judged',1900),S('Weightlifting','Lightweight','attempt'),S('Weightlifting','Heavyweight','attempt'),S('Wrestling','Greco-Roman','judged'),S('Shooting','Rifle','attempt'),S('Shooting','Pistol','attempt'),S('Tennis','Singles','team'),
 S('Rowing','Single Sculls','race',1900),S('Rowing','Coxed Pairs','race',1900),S('Rowing','Coxed Fours','race',1900),S('Rowing','Eights','race',1900),
 A('5000m','race',1900),A('10000m','race',1900),A('3000m Steeplechase','race',1900),A('Hammer Throw','attempt',1900),A('Standing Long Jump','attempt',1900),A('Standing High Jump','attempt',1900),
 S('Swimming','200m Freestyle','race',1900),S('Swimming','200m Backstroke','race',1900),S('Swimming','200m Team Race','race',1900),
 S('Sailing','0.5–1 Ton Class','race',1900),S('Sailing','1–2 Ton Class','race',1900),S('Sailing','Open Class','race',1900),
 S('Archery','Au Cordon Doré','attempt',1900),S('Archery','Au Chapelet','attempt',1900),S('Equestrian','Individual Jumping','judged',1900),S('Equestrian','High Jump','attempt',1900),
 S('Golf','Individual','attempt',1900),S('Golf','Individual','attempt',1900,'W'),S('Football','Tournament Final','team',1900),S('Rugby Union','Tournament Final','team',1900),S('Water Polo','Tournament Final','team',1900),S('Polo','Tournament Final','team',1900),
 S('Boxing','Flyweight','judged',1904),S('Boxing','Lightweight','judged',1904),S('Boxing','Middleweight','judged',1904),S('Boxing','Heavyweight','judged',1904),S('Diving','Platform','judged',1904),
 A('100m','race',1928,'W'),A('200m','race',1948,'W'),A('400m','race',1964,'W'),A('800m','race',1928,'W'),A('1500m','race',1972,'W'),A('Marathon','race',1984,'W'),A('100m Hurdles','race',1932,'W'),A('High Jump','attempt',1928,'W'),A('Long Jump','attempt',1948,'W'),A('Javelin','attempt',1932,'W'),A('Shot Put','attempt',1948,'W'),
 S('Swimming','100m Freestyle','race',1912,'W'),S('Swimming','400m Freestyle','race',1924,'W'),S('Swimming','100m Backstroke','race',1924,'W'),S('Gymnastics','All-Around','judged',1928,'W'),S('Gymnastics','Vault','judged',1952,'W'),S('Diving','Platform','judged',1912,'W'),S('Fencing','Foil','judged',1924,'W'),S('Tennis','Singles','team',1900,'W'),
 S('Basketball','Tournament Final','team',1936),S('Basketball','Tournament Final','team',1976,'W'),S('Volleyball','Tournament Final','team',1964),S('Volleyball','Tournament Final','team',1964,'W'),S('Judo','Middleweight','judged',1964),S('Judo','Middleweight','judged',1992,'W')
];
const templatesFor=(y:number)=>T.filter(x=>x.from<=y);
function makeAthlete(year:number,t:Template,i:number):Athlete{const country=pick(countryPool(year));return{id:`a-${year}-${t.name}-${i}-${Math.random()}`,name:randomAthleteName(country,t.gender),country,gender:t.gender,sport:t.sport,event:t.name,born:year-(18+rand(15)),overall:67+rand(28),potential:78+rand(21),form:68+rand(29),trait:pick(TRAITS),medals:0,golds:0,appearances:0,retired:false}}
function createAthletes(y:number){return templatesFor(y).flatMap(t=>Array.from({length:5},(_,i)=>makeAthlete(y,t,i)))}
function score(a:Athlete,y:number){return a.overall+a.form*.15+Math.random()*14-Math.max(0,age(a,y)-34)*1.2}
function field(t:Template,athletes:Athlete[],y:number){let p=athletes.filter(a=>!a.retired&&a.event===t.name&&a.gender===t.gender);while(p.length<5){const a=makeAthlete(y,t,p.length);athletes.push(a);p.push(a)}return [...p].sort((a,b)=>score(b,y)-score(a,y)).slice(0,5)}
function performance(e:FinalEvent,a:Athlete,y:number,r:number){const era=Math.min(1.25,(y-1896)/132);if(e.name.includes('100m'))return `${Math.max(9.45,12.25-era*2.25-(a.overall-70)*.017+r*.16+Math.random()*.03).toFixed(2)}s`;if(e.name.includes('200m'))return `${Math.max(19.1,25.2-era*4.5-(a.overall-70)*.035+r*.32+Math.random()*.06).toFixed(2)}s`;if(e.name.includes('400m'))return `${Math.max(42.3,56.8-era*10-(a.overall-70)*.07+r*.55+Math.random()*.12).toFixed(2)}s`;if(e.name.includes('800m'))return `1:${String(Math.max(40,59-Math.round(era*12+(a.overall-70)*.12-r))).padStart(2,'0')}.${rand(10)}`;if(e.name.includes('1500m'))return `3:${String(Math.max(24,59-Math.round(era*22+(a.overall-70)*.15-r*2))).padStart(2,'0')}.${rand(10)}`;if(e.name.includes('Marathon'))return `${Math.max(2,3-Math.floor(era))}:${String(Math.max(3,52-Math.floor(era*34)-(a.overall-70)/2+r*3)).padStart(2,'0')}:${String(rand(60)).padStart(2,'0')}`;if(e.name.includes('Jump')||e.name.includes('Vault'))return `${(1.65+era*.65+(a.overall-70)*.01-r*.06+Math.random()*.01).toFixed(2)}m`;if(e.name.includes('Javelin')||e.name.includes('Discus')||e.name.includes('Shot'))return `${(42+era*38+(a.overall-70)*.38-r*1.6+Math.random()*.25).toFixed(2)}m`;if(e.kind==='judged')return `${(7.1+(a.overall-70)*.075-r*.22+Math.random()*.04).toFixed(2)}`;if(e.kind==='team')return `${72+rand(35)}–${65+rand(30)}`;return `${(50+rand(120)/10).toFixed(2)}`}
function narrative(field:Athlete[],y:number){const top=field[0],second=field[1],third=field[2];if(top.golds>=4)return `History can be made. ${top.name} will attempt to claim a fifth Olympic gold.`;if(age(top,y)<=21)return `Can the young promise begin with gold? At only ${age(top,y)}, ${top.name} enters a first great Olympic test.`;if(Math.abs(top.overall-third.overall)<=3)return `An exceptionally competitive final is expected. ${top.name}, ${second.name} and ${third.name} are separated by almost nothing.`;if(age(top,y)>=34)return `${top.name} enters what may be a final Olympic appearance, with one more title still within reach.`;return `${top.name} starts as favorite, but ${second.name} has the form to challenge and Olympic finals rarely follow the script.`}
function makeEvents(y:number,athletes:Athlete[]){const items=templatesFor(y).map((t,i)=>{const f=field(t,athletes,y),gap=f[0].overall-f[1].overall,drama=(gap<3?5:0)+(f.some(a=>a.golds>1)?4:0)+(f.some(a=>age(a,y)>33)?3:0)+Math.random()*4;return{t,i,f,drama}});const target=Math.min(12,Math.max(8,Math.round(items.length*.18)));const star=new Set([...items].sort((a,b)=>b.drama-a.drama).slice(0,target).map(x=>x.i));return items.map(({t,i,f,drama})=>({id:`e-${y}-${i}`,day:1+(i%12),sport:t.sport,name:t.name,gender:t.gender,kind:t.kind,star:star.has(i),stars:star.has(i)?Math.min(6,3+Math.floor(drama/3)):1,hook:narrative(f,y),contenders:f.map(a=>a.id),resolved:false,results:[]} as FinalEvent))}
function resolve(e:FinalEvent,athletes:Athlete[],y:number){const f=e.contenders.map(id=>athletes.find(a=>a.id===id)!).filter(Boolean),ordered=[...f].sort((a,b)=>score(b,y)-score(a,y));const results=ordered.slice(0,3).map((a,i)=>({athleteId:a.id,name:a.name,country:a.country,mark:performance(e,a,y,i),medal:(['gold','silver','bronze'][i] as Result['medal'])}));const favorite=f[0],winner=ordered[0];let headline=winner.id!==favorite.id?`Big upset! ${winner.name} defeats favorite ${favorite.name}, who finishes ${ordered.indexOf(favorite)===1?'with silver':'outside the top two'}.`:`${winner.name} confirms the favorite's status and becomes Olympic champion.`;if(winner.golds>=4)headline=`History made: ${winner.name} claims a fifth Olympic gold.`;const out={...e,resolved:true,results,headline};
 if(e.kind==='race'){out.progress=Array.from({length:e.name.includes('100m')?10:5},(_,r)=>f.map((a,i)=>Math.min(100,(r+1)*(e.name.includes('100m')?10:20)+(score(a,y)-score(f[0],y))*.32+(Math.random()-.5)*7+(i===ordered.indexOf(winner)&&r>2?r*1.2:0))))}
 if(e.kind==='attempt'||e.kind==='judged')out.roundScores=Array.from({length:e.kind==='attempt'?5:4},()=>f.map(a=>Math.max(5,7.1+(a.overall-70)*.07+(Math.random()-.45)*1.1)));
 if(e.kind==='team'){let a=0,b=0;out.teamScores=Array.from({length:4},(_,r)=>{a+=14+rand(18);b+=14+rand(18);if(r===3&&winner.id===f[0].id&&a<=b)a=b+3+rand(8);if(r===3&&winner.id===f[1]?.id&&b<=a)b=a+3+rand(8);return[a,b]})}
 return out}
function hostOptions(y:number){const preferred=HOSTS[Math.max(0,Math.floor((y-1900)/4))%HOSTS.length];return Array.from(new Set([preferred,pick(HOSTS),pick(HOSTS)])).slice(0,3)}
function qualification(total:number):Qualification{return{total,closed:0,counts:Object.fromEntries(COUNTRIES.map(c=>[c,0])),news:['The qualification cycle has opened. Every nation begins with a blank slate.']}}
function initial():Save{const athletes=createAthletes(1896);return{version:3,year:1896,olympicYear:1896,host:'Athens',pendingHost:false,phase:'between',day:1,athletes,events:[],medals:blankMedals(),qualification:qualification(templatesFor(1896).length),history:[],annualNews:['Athens prepares to revive the Olympic Games after more than fifteen centuries.']}}

export default function App(){
 const [save,setSave]=useState<Save>(()=>{try{const p=JSON.parse(localStorage.getItem('olympic-chronicles-v4')||'null');return p?.version===3?p:initial()}catch{return initial()}});
 const [view,setView]=useState<'chronicle'|'qualification'|'games'|'athletes'|'almanac'>('chronicle'); const [gamesTab,setGamesTab]=useState<'daily'|'all'|'medals'>('daily');
 const [preview,setPreview]=useState<string|null>(null),[watch,setWatch]=useState<FinalEvent|null>(null),[watchStep,setWatchStep]=useState(0),[result,setResult]=useState<string|null>(null);
 const persist=(s:Save)=>{setSave(s);try{const compact={...s,events:s.events.map(({progress,roundScores,teamScores,...event})=>event)};localStorage.setItem('olympic-chronicles-v4',JSON.stringify(compact))}catch(error){console.warn('Save could not be written',error)}};
 const event=save.events.find(e=>e.id===preview),watchEvent=watch,resultEvent=save.events.find(e=>e.id===result);
 const medalRows=useMemo(()=>Object.entries(save.medals).sort((a,b)=>b[1].gold-a[1].gold||b[1].silver-a[1].silver||b[1].bronze-a[1].bronze),[save.medals]);
 const today=save.events.filter(e=>e.day===save.day), active=[...save.athletes].filter(a=>!a.retired).sort((a,b)=>b.overall-a.overall);
 function selectHost(h:string){const nextYear=save.olympicYear===1896?1900:save.olympicYear+4;const y=save.olympicYear+1;persist({...save,year:y,olympicYear:nextYear,host:h,pendingHost:false,phase:'between',events:[],day:1,medals:blankMedals(),qualification:qualification(templatesFor(nextYear).length),annualNews:[`${h} has been selected to host the ${nextYear} Olympic Games. Qualification has officially begun.`]});setView('qualification')}
 function open1896(){const athletes=[...save.athletes];persist({...save,phase:'games',events:makeEvents(1896,athletes),athletes,day:1});setView('games')}
 function advanceYear(){if(save.year>=save.olympicYear){const athletes=[...save.athletes];persist({...save,phase:'games',events:makeEvents(save.olympicYear,athletes),athletes,day:1,medals:blankMedals()});setView('games');return}const y=save.year+1;let athletes=save.athletes.map(a=>({...a,form:65+rand(31),overall:Math.min(a.potential,a.overall+(Math.random()<.55?rand(2):0)),retired:a.retired||(age(a,y)>36&&Math.random()<.35)}));templatesFor(save.olympicYear).forEach(t=>{if(athletes.filter(a=>!a.retired&&a.event===t.name).length<5)athletes.push(...Array.from({length:3},(_,i)=>makeAthlete(y,t,i)))});const q={...save.qualification,counts:{...save.qualification.counts},news:[...save.qualification.news]};const target=Math.min(q.total,Math.round(q.total*((y-(save.olympicYear-4))/4)));while(q.closed<target){q.closed++;const c=pick(countryPool(y));q.counts[c]=(q.counts[c]||0)+1;if(q.counts[c]===1)q.news.unshift(`${NAMES[c]} has placed its first athlete or team into the ${save.olympicYear} Games.`)}const star=athletes.filter(a=>!a.retired).sort((a,b)=>b.overall-a.overall)[rand(8)];q.news.unshift(`${star.name} (${star.country}) secures qualification in ${star.event}.`);persist({...save,year:y,athletes,qualification:q,annualNews:[q.news[0],`${q.closed} of ${q.total} Olympic contests now have confirmed qualifiers.`,`${NAMES[pick(countryPool(y))]} announces a major investment in elite coaching.`]})}
 function applyResolved(r:FinalEvent){let medals={...save.medals};let athletes=[...save.athletes];r.results.forEach(x=>{medals={...medals,[x.country]:{...medals[x.country],[x.medal]:medals[x.country][x.medal]+1}};athletes=athletes.map(a=>a.id===x.athleteId?{...a,medals:a.medals+1,golds:a.golds+(x.medal==='gold'?1:0),appearances:a.appearances+1}:a)});persist({...save,events:save.events.map(e=>e.id===r.id?r:e),medals,athletes})}
 function simulateEvent(e:FinalEvent,showResult=true){const r=resolve(e,save.athletes,save.olympicYear);applyResolved(r);setPreview(null);if(showResult)setResult(e.id)}
 function nextEvent(){const e=today.find(x=>!x.resolved);if(!e)return;if(e.star)setPreview(e.id);else simulateEvent(e,true)}
 function simulateAllNormal(){let s=save;today.filter(e=>!e.resolved&&!e.star).forEach(e=>{const r=resolve(e,s.athletes,s.olympicYear);let medals={...s.medals};let athletes=[...s.athletes];r.results.forEach(x=>{medals={...medals,[x.country]:{...medals[x.country],[x.medal]:medals[x.country][x.medal]+1}};athletes=athletes.map(a=>a.id===x.athleteId?{...a,medals:a.medals+1,golds:a.golds+(x.medal==='gold'?1:0)}:a)});s={...s,events:s.events.map(x=>x.id===r.id?r:x),medals,athletes}});persist(s)}
 function moveDay(){if(today.some(e=>!e.resolved))return;if(save.day<12)persist({...save,day:save.day+1});else persist({...save,phase:'complete'})}
 function closeGames(){const champ=medalRows[0]?.[0]||'USA',memory=save.events.filter(e=>e.star&&e.headline).slice(0,4).map(e=>e.headline).join(' ');persist({...save,phase:'complete',pendingHost:true,history:[...save.history,{year:save.olympicYear,host:save.host,champion:champ,memory}],annualNews:[`${save.host} ${save.olympicYear} enters history. ${NAMES[champ]} led the medal table.`]});setView('chronicle')}
 const opts=hostOptions(save.olympicYear+4);
 return <div className={styles.app}>
  <header className={styles.topbar}><div><span className={styles.kicker}>OLYMPIC</span><strong>CHRONICLES</strong></div><div className={styles.era}>{save.host} {save.olympicYear} · {save.year}</div><button className={styles.reset} onClick={()=>{localStorage.removeItem('olympic-chronicles-v4');location.reload()}}>New history</button></header>
  <nav className={styles.nav}>{(['chronicle','qualification','games','athletes','almanac'] as const).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?styles.navActive:''}>{v}</button>)}</nav>
  {save.pendingHost&&<div className={styles.hostOverlay}><div className={styles.hostPanel}><span className={styles.eyebrow}>Host selection · {save.olympicYear+4}</span><h1>Where will the next Olympiad be held?</h1><p>The host is selected immediately after the prior Games. Its nation receives a modest home advantage and shapes the next cycle's identity.</p><div className={styles.hostGrid}>{opts.map((h,i)=><button key={h} onClick={()=>selectHost(h)}><Flag code={HOST_COUNTRY[h]||'GRE'} size={42}/><small>CANDIDATE {i+1}</small><b>{h}</b><span>{i===0?'Established sporting capital':i===1?'Ambitious expanding bid':'A bold new Olympic chapter'}</span></button>)}</div></div></div>}
  {view==='chronicle'&&<main className={styles.layout}><section className={styles.hero}><div><span className={styles.eyebrow}>{save.phase==='games'?`THE GAMES ARE UNDERWAY`:save.olympicYear===1896?'THE FIRST MODERN OLYMPIAD':`${save.olympicYear-save.year} YEARS TO ${save.host.toUpperCase()}`}</span><h1>{save.olympicYear===1896?'The Olympic story begins in Athens.':'Champions rise long before the flame is lit.'}</h1><p>Follow qualification, emerging stars, changing national programs and the stories that make the Games the final ecstasy of each four-year cycle.</p></div><div className={styles.yearCard}><small>THE YEAR</small><b>{save.year}</b><span>{templatesFor(save.olympicYear).length} medal contests</span></div></section><section className={styles.section}><span className={styles.eyebrow}>Annual chronicle</span><h2>What changed this year</h2><div className={styles.storyGrid}>{save.annualNews.map((n,i)=><article className={`${styles.story} ${[styles.gold,styles.blue,styles.green][i%3]}`} key={i}><small>{i===0?'LEAD STORY':'FROM THE OLYMPIC WORLD'}</small><h3>{n}</h3></article>)}</div></section><button className={styles.primary} onClick={save.olympicYear===1896&&save.phase==='between'?open1896:save.phase==='games'?()=>setView('games'):advanceYear}>{save.olympicYear===1896&&save.phase==='between'?'Open Athens 1896':save.phase==='games'?'Return to the Games':save.year>=save.olympicYear?'Begin the Olympic Games':'Advance one year'} →</button></main>}
  {view==='qualification'&&<main className={styles.layout}><section className={styles.gamesHero}><div><span className={styles.eyebrow}>ROAD TO {save.host.toUpperCase()} {save.olympicYear}</span><h1>{save.qualification.closed}/{save.qualification.total} contests closed</h1><p>Qualification develops throughout the four-year cycle. Star debuts and first national entries become part of the chronicle.</p></div><div className={styles.yearCard}><small>QUALIFIED ENTRIES</small><b>{Object.values(save.qualification.counts).reduce((a,b)=>a+b,0)}</b><span>{Object.values(save.qualification.counts).filter(Boolean).length} nations represented</span></div></section><section className={styles.split}><div className={styles.panel}><span className={styles.eyebrow}>Qualification standings</span>{Object.entries(save.qualification.counts).sort((a,b)=>b[1]-a[1]).slice(0,18).map(([c,n],i)=><div className={styles.athleteRow} key={c}><b>{i+1}</b><Flag code={c} size={28}/><div><strong>{NAMES[c]}</strong><span>{n} athletes / teams</span></div><em>{n}</em></div>)}</div><div className={styles.panel}><span className={styles.eyebrow}>Qualification news</span>{save.qualification.news.slice(0,12).map((n,i)=><div className={styles.qualNews} key={i}><small>{i+1}</small><p>{n}</p></div>)}</div></section>{save.phase==='between'&&<button className={styles.primary} onClick={advanceYear}>{save.year>=save.olympicYear?'Begin the Games':'Advance qualification year'} →</button>}</main>}
  {view==='games'&&<main className={styles.layout}><section className={styles.gamesHero}><div><span className={styles.eyebrow}>{save.host.toUpperCase()} {save.olympicYear}</span><h1>{save.phase==='complete'?'The Games enter history':`Day ${save.day} of 12`}</h1><p>{save.phase==='complete'?'The medal race is over. The great performances and disappointments are now part of the archive.':'Every final is listed by day. Ordinary finals resolve quickly; Star Events can be watched without spoilers.'}</p></div><div className={styles.rings}>◯ ◯ ◯ ◯ ◯</div></section><div className={styles.subTabs}>{(['daily','all','medals'] as const).map(t=><button className={gamesTab===t?styles.navActive:''} onClick={()=>setGamesTab(t)} key={t}>{t==='daily'?'DAILY RESULTS':t==='all'?'ALL RESULTS':'MEDAL TABLE'}</button>)}</div>
  {save.phase==='complete'?<section className={styles.memory}><span className={styles.eyebrow}>How history remembers the Games</span><h2>{save.host} {save.olympicYear}</h2><p>{save.events.filter(e=>e.star&&e.headline).slice(0,5).map(e=>e.headline).join(' ')}</p><button className={styles.primary} onClick={closeGames}>Select the next host →</button></section>:gamesTab==='medals'?<Medals rows={medalRows}/>:gamesTab==='all'?<AllResults events={save.events}/>:<><div className={styles.dayNav}>{Array.from({length:12},(_,i)=>i+1).map(d=><button key={d} className={d===save.day?styles.dayActive:''} onClick={()=>persist({...save,day:d})}>DAY {d}</button>)}</div><section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>Daily program</span><h2>Finals on Day {save.day}</h2></div><span>{today.filter(e=>e.resolved).length}/{today.length} complete</span></div><div className={styles.eventGrid}>{today.map(e=><article key={e.id} className={`${styles.eventCard} ${e.star?styles.starCard:''}`}><div className={styles.eventTop}><span>{e.sport}</span><span>{e.star?'★ STAR EVENT':'FINAL'}</span></div><h3>{e.name}</h3><p>{e.resolved?e.headline:e.hook}</p>{e.resolved?<div className={styles.podiumMini}>{e.results.map(r=><div key={r.medal}><span>{r.medal==='gold'?'🥇':r.medal==='silver'?'🥈':'🥉'}</span><Flag code={r.country} size={22}/><b>{r.name}</b><em>{r.mark}</em></div>)}</div>:<div className={styles.favorite}><b>{save.athletes.find(a=>a.id===e.contenders[0])?.name}</b><span>{e.star?'Marquee final — preview available':'Qualified field ready'}</span></div>} {!e.resolved&&e.star&&<button onClick={()=>setPreview(e.id)}>Open event preview</button>}</article>)}</div></section><div className={styles.actionRow}><button className={styles.secondary} onClick={nextEvent}>Simulate next event</button><button className={styles.secondary} onClick={simulateAllNormal}>Simulate all normal events</button><button className={styles.primary} disabled={today.some(e=>!e.resolved)} onClick={moveDay}>{save.day===12?'Finish the Games':'Next day'} →</button></div></>}</main>}
  {view==='athletes'&&<main className={styles.layout}><section className={styles.section}><span className={styles.eyebrow}>Living careers</span><h1>Athletes of the age</h1><div className={styles.athleteGrid}>{active.slice(0,50).map(a=><article className={styles.athleteCard} key={a.id}><Flag code={a.country} size={34}/><small>{a.country} · {a.sport}</small><h3>{a.name}</h3><p>{a.event}</p><div className={styles.metrics}><span><b>{a.overall}</b> rating</span><span><b>{age(a,save.year)}</b> age</span><span><b>{a.golds}</b> gold</span></div><em>{a.trait}</em></article>)}</div></section></main>}
  {view==='almanac'&&<main className={styles.layout}><section className={styles.section}><span className={styles.eyebrow}>Historical archive</span><h1>Olympic Almanac</h1><div className={styles.historyGrid}>{[...save.history].reverse().map(h=><article className={styles.historyCard} key={h.year}><small>{h.host}</small><h2>{h.year}</h2><b><Flag code={h.champion} size={22}/> {NAMES[h.champion]} led the medal table</b><p>{h.memory}</p></article>)}</div></section></main>}
  {event&&<Preview event={event} athletes={save.athletes} year={save.olympicYear} close={()=>setPreview(null)} simulate={()=>simulateEvent(event,true)} view={()=>{const r=resolve(event,save.athletes,save.olympicYear);applyResolved(r);setPreview(null);setWatch(r);setWatchStep(0)}}/>}
  {watchEvent&&<Watch event={watchEvent} athletes={save.athletes} step={watchStep} setStep={setWatchStep} close={()=>{setWatch(null);setResult(watchEvent.id)}}/>}
  {resultEvent&&<ResultModal event={resultEvent} close={()=>setResult(null)}/>} 
 </div>}

function Medals({rows}:{rows:[string,{gold:number;silver:number;bronze:number}][]}){return <section className={styles.section}><h2>Full medal table</h2><div className={styles.scoreTable}><div className={styles.scoreHead}><span>NATION</span><b>GOLD</b><b>SILVER</b><b>BRONZE</b></div>{rows.map(([c,m],i)=><div key={c}><span><b>{i+1}</b> <Flag code={c} size={24}/> {NAMES[c]}</span><em>{m.gold}</em><em>{m.silver}</em><em>{m.bronze}</em></div>)}</div></section>}
function AllResults({events}:{events:FinalEvent[]}){return <section className={styles.section}><h2>All Olympic finals</h2>{Array.from(new Set(events.map(e=>e.sport))).map(s=><div className={styles.allSport} key={s}><h3>{s}</h3>{events.filter(e=>e.sport===s).map(e=><div key={e.id}><b>{e.name}</b><span>{e.resolved?`${e.results[0]?.name} (${e.results[0]?.country}) — ${e.results[0]?.mark}`:`Day ${e.day} · Pending`}</span></div>)}</div>)}</section>}
function Preview({event,athletes,year,close,simulate,view}:{event:FinalEvent;athletes:Athlete[];year:number;close:()=>void;simulate:()=>void;view:()=>void}){const f=event.contenders.map(id=>athletes.find(a=>a.id===id)!).filter(Boolean);return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.close} onClick={close}>×</button><span className={styles.eyebrow}>STAR EVENT · {event.sport}</span><h2>{event.name}</h2><p className={styles.previewStory}>{event.hook}</p><div className={styles.liveRows}>{f.map(a=><div key={a.id}><Flag code={a.country} size={28}/><b>{a.name}</b><span>{a.country} · age {age(a,year)} · {a.trait}</span><strong>{a.overall}</strong></div>)}</div><div className={styles.actionRow}><button className={styles.secondary} onClick={simulate}>Simulate</button><button className={styles.primary} onClick={view}>View event →</button></div></div></div>}
function Watch({event,athletes,step,setStep,close}:{event:FinalEvent;athletes:Athlete[];step:number;setStep:(n:number)=>void;close:()=>void}){const f=event.contenders.map(id=>athletes.find(a=>a.id===id)!).filter(Boolean);const max=event.kind==='race'?(event.progress?.length||1)-1:event.kind==='team'?(event.teamScores?.length||1)-1:(event.roundScores?.length||1)-1;const done=step>max;return <div className={styles.modalBackdrop}><div className={styles.modal}><span className={styles.eyebrow}>LIVE · {event.sport}</span><h2>{event.name}</h2>{!done&&event.kind==='race'&&<><div className={styles.liveClock}>{event.name.includes('100m')?`${step+1}.0s`:`CHECKPOINT ${step+1}`}</div><div className={styles.liveRows}>{f.map((a,i)=>{const d=event.progress?.[step]?.[i]||0;return <div key={a.id}><Flag code={a.country} size={26}/><b>{a.name}</b><span>{a.country}</span><strong>{d>=99?event.results.find(r=>r.athleteId===a.id)?.mark:`${d.toFixed(1)}m`}</strong><div className={styles.track}><i style={{width:`${Math.min(100,d)}%`}}/></div></div>})}</div></>}{!done&&(event.kind==='attempt'||event.kind==='judged')&&<div className={styles.scoreTable}><div className={styles.scoreHead}><span>ATHLETE</span>{event.roundScores?.map((_,i)=><b key={i}>RD{i+1}</b>)}</div>{f.map((a, athleteIndex) => (
  <div key={a.id}>
    <span>
      <Flag code={a.country} size={23} />
      <b>{a.name}</b>
    </span>

    {event.roundScores?.map((round, roundIndex) => (
      <em key={roundIndex}>
        {roundIndex <= step
          ? round[athleteIndex].toFixed(2)
          : '—'}
      </em>
    ))}
  </div>
))}</div>}{!done&&event.kind==='team'&&<div className={styles.teamWatch}><div><Flag code={f[0]?.country} size={42}/><h3>{f[0]?.country}</h3><strong>{event.teamScores?.[step]?.[0]}</strong></div><span>{step===3?'FINAL':`Q${step+1}`}</span><div><Flag code={f[1]?.country} size={42}/><h3>{f[1]?.country}</h3><strong>{event.teamScores?.[step]?.[1]}</strong></div></div>}{done?<button className={styles.primary} onClick={close}>See final results →</button>:<button className={styles.primary} onClick={()=>setStep(step+1)}>{step===max?'Reveal result':'Next '+(event.kind==='race'?'checkpoint':'round')} →</button>}</div></div>}
function ResultModal({event,close}:{event:FinalEvent;close:()=>void}){return <div className={styles.modalBackdrop}><div className={styles.modal}><button className={styles.close} onClick={close}>×</button><span className={styles.eyebrow}>FINAL RESULT · {event.sport}</span><h2>{event.name}</h2><div className={styles.reveal}><small>OLYMPIC CHAMPION</small><h3>{event.results[0]?.name}</h3><div className={styles.championFlag}><Flag code={event.results[0]?.country} size={46}/>{NAMES[event.results[0]?.country]}</div><b>{event.results[0]?.mark}</b><p>{event.headline}</p><div className={styles.finalPodium}>{event.results.map(r=><div key={r.medal}><span>{r.medal.toUpperCase()}</span><Flag code={r.country} size={24}/><b>{r.name}</b><em>{r.mark}</em></div>)}</div></div></div></div>}
